# https://docs.codecov.io/docs/codecovyml-reference
# https://docs.codecov.io/docs/coverage-configuration
ignore:
  - "cmd/leges/main.go"
coverage:
  precision: 1
  range: "40...80"
  round: nearest
  status:
    patch:
      default:
        target: 60%
        threshold: 10%
    project:
      default:
        target: 60%
        threshold: 10%
